
server:
  port: 8070

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/kotlin_demo"
    username: "root"
    password: "password"

  jpa:
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
    database: MYSQL
    open-in-view: true
    hibernate:
      ddl-auto: update

